const blogdata = [
	{
		id: 1,
		title: "THE EASIEST WAY TO BREAK",
		excerpt:
			"But I must explain to you how all this mistaken idea of denouncing pleas and praising pain was bor",
		image:
			"https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
		date: "2020-05-20",
		blog: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste exercitationem veniam itaque asperiores aliquid? Aut labore quasi obcaecati ea non, est voluptate quis hic rerum amet voluptas qui cupiditate alias velit corporis molestias officia expedita repellendus sunt exercitationem distinctio adipisci necessitatibus? Totam rem quibusdam sequi enim. Mollitia libero ut atque nesciunt! Illo enim tempora nemo voluptatum cum in itaque omnis nulla, provident repellat totam molestiae ea quo. Expedita neque tempora repudiandae soluta quod facere maiores repellat non eum reprehenderit inventore aliquam, necessitatibus corporis id quae! Possimus similique cumque ipsam deserunt eveniet, enim debitis quibusdam culpa, nemo, hic laborum velit voluptas ea. Quibusdam quidem ratione labore voluptate est non dolor. Eveniet, vitae voluptates porro neque recusandae assumenda veritatis temporibus, autem amet ipsum, beatae deleniti impedit deserunt cupiditate a. Commodi nihil beatae est voluptate aspernatur, et earum at vitae officiis? Amet incidunt temporibus libero neque dolorem odio deserunt non nemo repellat velit minima, ratione officiis voluptas quo iusto nesciunt? Distinctio assumenda commodi, odio iste labore voluptatem dolores veritatis reprehenderit ut eveniet quae enim debitis sed corrupti nesciunt nemo laborum sint eum hic repellendus, molestias qui id! Et molestias dolorum aspernatur ratione. Suscipit assumenda, deserunt tempore, eveniet quos fugiat explicabo repudiandae quisquam qui voluptate culpa eligendi quia repellat ipsum, repellendus provident placeat. Harum eius facilis nam commodi nihil ab debitis quam omnis ducimus beatae animi enim, corporis suscipit blanditiis molestias earum eaque, repellendus ipsa saepe? Repellendus corrupti aliquam amet, cum et eos iste fugit alias deserunt laboriosam eaque quidem impedit, mollitia a praesentium laborum vitae sequi, est saepe animi. Sed nihil ut quis enim. Suscipit cum impedit asperiores quidem minima illo, sint veritatis vero alias et doloremque amet placeat repellendus. Sapiente deleniti libero officiis cumque. Culpa ipsum nobis repellendus iusto tempore nulla minus voluptate laudantium quae blanditiis aliquid quas, dignissimos autem labore sunt?",
	},
	{
		id: 2,
		title: "Wedding Season",
		excerpt:
			"But I must explain to you how all this mistaken idea of denouncing pleas and praising pain was bor",
		image:
			"https://images.unsplash.com/photo-1549488497-94b52bddac5d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
		date: "2020-05-20",
		blog: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste exercitationem veniam itaque asperiores aliquid? Aut labore quasi obcaecati ea non, est voluptate quis hic rerum amet voluptas qui cupiditate alias velit corporis molestias officia expedita repellendus sunt exercitationem distinctio adipisci necessitatibus? Totam rem quibusdam sequi enim. Mollitia libero ut atque nesciunt! Illo enim tempora nemo voluptatum cum in itaque omnis nulla, provident repellat totam molestiae ea quo. Expedita neque tempora repudiandae soluta quod facere maiores repellat non eum reprehenderit inventore aliquam, necessitatibus corporis id quae! Possimus similique cumque ipsam deserunt eveniet, enim debitis quibusdam culpa, nemo, hic laborum velit voluptas ea. Quibusdam quidem ratione labore voluptate est non dolor. Eveniet, vitae voluptates porro neque recusandae assumenda veritatis temporibus, autem amet ipsum, beatae deleniti impedit deserunt cupiditate a. Commodi nihil beatae est voluptate aspernatur, et earum at vitae officiis? Amet incidunt temporibus libero neque dolorem odio deserunt non nemo repellat velit minima, ratione officiis voluptas quo iusto nesciunt? Distinctio assumenda commodi, odio iste labore voluptatem dolores veritatis reprehenderit ut eveniet quae enim debitis sed corrupti nesciunt nemo laborum sint eum hic repellendus, molestias qui id! Et molestias dolorum aspernatur ratione. Suscipit assumenda, deserunt tempore, eveniet quos fugiat explicabo repudiandae quisquam qui voluptate culpa eligendi quia repellat ipsum, repellendus provident placeat. Harum eius facilis nam commodi nihil ab debitis quam omnis ducimus beatae animi enim, corporis suscipit blanditiis molestias earum eaque, repellendus ipsa saepe? Repellendus corrupti aliquam amet, cum et eos iste fugit alias deserunt laboriosam eaque quidem impedit, mollitia a praesentium laborum vitae sequi, est saepe animi. Sed nihil ut quis enim. Suscipit cum impedit asperiores quidem minima illo, sint veritatis vero alias et doloremque amet placeat repellendus. Sapiente deleniti libero officiis cumque. Culpa ipsum nobis repellendus iusto tempore nulla minus voluptate laudantium quae blanditiis aliquid quas, dignissimos autem labore sunt?",
	},
	{
		id: 3,
		title: "RECENT FAVORITES ON REPEAT",
		excerpt:
			"But I must explain to you how all this mistaken idea of denouncing pleas and praising pain was bor",
		image:
			"https://images.unsplash.com/photo-1496747611176-843222e1e57c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1473&q=80",
		date: "2020-05-20",
		blog: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste exercitationem veniam itaque asperiores aliquid? Aut labore quasi obcaecati ea non, est voluptate quis hic rerum amet voluptas qui cupiditate alias velit corporis molestias officia expedita repellendus sunt exercitationem distinctio adipisci necessitatibus? Totam rem quibusdam sequi enim. Mollitia libero ut atque nesciunt! Illo enim tempora nemo voluptatum cum in itaque omnis nulla, provident repellat totam molestiae ea quo. Expedita neque tempora repudiandae soluta quod facere maiores repellat non eum reprehenderit inventore aliquam, necessitatibus corporis id quae! Possimus similique cumque ipsam deserunt eveniet, enim debitis quibusdam culpa, nemo, hic laborum velit voluptas ea. Quibusdam quidem ratione labore voluptate est non dolor. Eveniet, vitae voluptates porro neque recusandae assumenda veritatis temporibus, autem amet ipsum, beatae deleniti impedit deserunt cupiditate a. Commodi nihil beatae est voluptate aspernatur, et earum at vitae officiis? Amet incidunt temporibus libero neque dolorem odio deserunt non nemo repellat velit minima, ratione officiis voluptas quo iusto nesciunt? Distinctio assumenda commodi, odio iste labore voluptatem dolores veritatis reprehenderit ut eveniet quae enim debitis sed corrupti nesciunt nemo laborum sint eum hic repellendus, molestias qui id! Et molestias dolorum aspernatur ratione. Suscipit assumenda, deserunt tempore, eveniet quos fugiat explicabo repudiandae quisquam qui voluptate culpa eligendi quia repellat ipsum, repellendus provident placeat. Harum eius facilis nam commodi nihil ab debitis quam omnis ducimus beatae animi enim, corporis suscipit blanditiis molestias earum eaque, repellendus ipsa saepe? Repellendus corrupti aliquam amet, cum et eos iste fugit alias deserunt laboriosam eaque quidem impedit, mollitia a praesentium laborum vitae sequi, est saepe animi. Sed nihil ut quis enim. Suscipit cum impedit asperiores quidem minima illo, sint veritatis vero alias et doloremque amet placeat repellendus. Sapiente deleniti libero officiis cumque. Culpa ipsum nobis repellendus iusto tempore nulla minus voluptate laudantium quae blanditiis aliquid quas, dignissimos autem labore sunt?",
	},
];

export default blogdata;
